### ISSUE TITLE
Tilelive-carto source fails with mkdir error on mml file

### ISSUE THREAD

**Issue by jflemer-ndp** [mojodna/tl#17]
Not sure if this is a bug in `tl` or [tilelive-carto](https://github.com/mojodna/tilelive-carto). The same tilelive-carto source seems to work with tessera though, so I suspect it's something about `tl copy`.
### To Reproduce

Run:

```
tl copy -r tilelive-carto -z 6 -Z 6 -b "-124.4096 32.5343 -114.1308 42.0095" carto+file://./project.mml mbtiles:///tmp/foo.mbtiles
```

And get output:

```
{ [Error: EEXIST: file already exists, mkdir '/tmp/style/project.mml']
  errno: -17,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: '/tmp/style/project.mml' }
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: EEXIST: file already exists, mkdir '/tmp/style/project.mml'
    at Error (native)
```

Note that the error (the `mkdir`) is originating in `tilelive-file` at https://github.com/mapbox/tilelive-file/blob/b31ef8477bf5b9785f0b3e6930f271423c33cf12/lib/tilelive-file.js#L29
### Workaround

Just use carto to compile the mml, then use `tl copy ... mapnik://./project.xml ...`
### Versions

```
tilelive@5.12.1
tilelive-file@0.0.3
tilelive-modules@0.2.0
tilelive-streaming@0.6.0
tl@0.6.0
```

**Comment by sethfitz** [comment]
`tilelive-carto` is kind of an ugly step-child. More of a proof of concept than anything. Potentially handy someday though.

`tilelive-file` shouldn't even be involved here (since that's about reading / writing tiles as files to/from the filesystem).

**Comment by jflemer-ndp** [comment]
Easy workaround, so no rush to fix this. 

I tried to figure out how tilelive-file was getting involved, but didn't see an obvious fix.

**Comment by sethfitz** [comment]
I stumbled around this a while back and finally figured out what the problem was:

`tilelive-streaming` was overwriting `sourceURI`: https://github.com/mojodna/tilelive-streaming/blob/b5acd255d3d9b49d01921210cea2f84f06233348/index.js#L531

The reason you were seeing it in `tl` and not `tessera` is that `tessera` was using an older version of `tilelive-streaming`.

FWIW, I tracked this down by adding a getter and setter for `sourceURI` in the constructor and logging the stack when the setter was called:

``` javascript
Object.defineProperty(this, "sourceURI", {
  set: function(x) {
    console.log("setting sourceURI to", x);
    console.log(new Error().stack);
    this._uri = x;
  },
  get: function() {
    return this._uri;
  }
});
```
